### ISSUE TITLE
Update documentation regarding .fail

### ISSUE THREAD

**Issue by danielheth** [mikeobrien/node-windows-service-controller#1]
It took me several hours to figure out you can add .fail to the examples and catch them.  Here is what i came up with that catches the situation when you're asking for a service that doesn't exist:

`return new Promise((resolve, reject) => {
            sc.query({
                name: 'MyMissingService',
                class: 'service'
            })
            .fail((err) => {
                caughtError = err;
                return [];
            })
            .done((services) => {
                if (!services || services.length === 0) {
                    if (!caughtError) {
                        caughtError = new Error('Unknown error has occurred.');
                    }
                    reject(caughtError);
                    return;
                }
                resolve({ Status: services[0].state.name });
            });
        });`

This is how i dealt with things in NodeJS and would be handy to have the docs updated and save others time researching.

**Comment by mikeobrien** [comment]
Yeah, all methods return a promise. [The docs already cover this and briefly demonstrate how to use them with this module](https://github.com/mikeobrien/node-windows-service-controller#usage) (`Fail` is an alias of `Catch`). You can learn more about promises [here](https://developers.google.com/web/fundamentals/getting-started/primers/promises). HTH
