### ISSUE TITLE
UAC Elevation

### ISSUE THREAD

**Issue by AshishShanker** [mikeobrien/node-windows-service-controller#3]
Not sure how to execute commands under an elevated privilege. 

If I was issuing, say, a  `sc create` command through the command prompt, I would typically do that at terminal opened with "Run as Administrator". 

If I use `node-windows-service-controller`'s sc.create, I get an "Access is denied" error which is understandable since the request does need elevated privileges to execute.

Note that I am trying to create a service on local machine under LocalSystem id, so nothing fancy here otherwise.

So my question: is it possible to do UAC elevation using `node-windows-service-controller`

**Comment by AshishShanker** [comment]
There is a hack-y workaround to this problem, essentially piping the command this package creates _internally_, into [`elevator`](https://github.com/resin-io-modules/elevator) another npm package  that wraps around [elevator.exe by kliu](http://code.kliu.org/misc/elevate/) that essentially does privilege escalation for you. Assuming you have `npm/npx install`ed `elevator`:
```
import sc from 'windows-service-controller/src/sc-command';
import elevator from 'elevator'

async (appName) => {
    try
    {    
        const cmd = await sc.create([appName, {binpath:`./path/to/${appName}.exe`}]);
        elevator.executeSync(`${cmd.path} ${cmd.args.join(' ')}`, 
                                                     {
                                                            terminating:true, 
                                                            hidden:true, 
                                                            waitForTermination:true, 
                                                           doNotPushdCurrentDirectory:true
                                                    });
    } catch (err) {
        console.log(err); // or whatever you want to do with an error
    }

}
```
The hackiness doesn't stop there though. Turns out the `cmd.path` and `cmd.args` don't always have the strings you need to assemble the command line to pass to `elevator.executeSync()`. For example, if you wanted to do `sc.stop`, the right way to assemble the string for `elevator.executeSync()` is as follows:

```
import sc from 'windows-service-controller/src/sc-command';
import elevator from 'elevator'

async (appName) => {
    try
    {    
        const cmd = await sc.stop([appName]);
        const args = cmd.commands[0].args.slice(0);
        args.unshift(cmd.command[0].path);
        elevator.executeSync(args, 
                                                     {
                                                            terminating:true, 
                                                            hidden:true, 
                                                            waitForTermination:true, 
                                                           doNotPushdCurrentDirectory:true
                                                    });
    } catch (err) {
        console.log(err); // or whatever you want to do with an error
    }

}

```
Hope this helps somebody :). Tested only on Win10

**Comment by mikeobrien** [comment]
Awesome, thx for sharing this solution!

**Comment by AshishShanker** [comment]
Hi @mikeobrien - would you have interest in collaborating on baking in UAC Elevation into the product? I feel there is a real value to it, but not sure if you feel this aligns well with where you want to take it.

**Comment by mcdado** [comment]
How about using `runas` and passing the user/password as parameters?
See: https://satob.hatenablog.com/entry/2017/06/17/013217
